# Generated by Django 5.0 on 2023-12-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='painting',
            options={'ordering': ['name'], 'verbose_name': 'Картина', 'verbose_name_plural': 'Картины'},
        ),
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddIndex(
            model_name='painting',
            index=models.Index(fields=['id', 'slug'], name='shop_painti_id_7d38a9_idx'),
        ),
        migrations.AddIndex(
            model_name='painting',
            index=models.Index(fields=['name'], name='shop_painti_name_f5efbf_idx'),
        ),
        migrations.AddIndex(
            model_name='painting',
            index=models.Index(fields=['-created'], name='shop_painti_created_613936_idx'),
        ),
    ]
