# Generated by Django 5.0 on 2023-12-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_painting_options_alter_painting_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(blank=True, upload_to='paintings/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
