# Generated by Django 5.0 on 2023-12-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_painting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='sold',
            field=models.BooleanField(blank=True, default=False, verbose_name='Продано'),
        ),
    ]
