# Generated by Django 5.0 on 2023-12-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_painting_sold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='painting',
            options={'ordering': ['-created'], 'verbose_name': 'Картина', 'verbose_name_plural': 'Картины'},
        ),
        migrations.AlterField(
            model_name='painting',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Продано'),
        ),
    ]
