# Generated by Django 5.0 on 2023-12-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orderitem_orderpainting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpainting',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
