# Generated by Django 5.0 on 2023-12-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderpainting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpainting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
