# Generated by Django 5.0 on 2023-12-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderpainting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не обработано'), (1, 'Обработано'), (2, 'Завершен'), (3, 'Отменен')], default=0, verbose_name='Статус'),
        ),
    ]
